import type { Preset, Rules } from './types';
const common = {
  rounds: 4,
  claimSeconds: 8,
  turnSeconds: 35,
  nextHandSeconds: 60,
  advanceWhenReady: true,
  hostCanAdvance: true,
  allowChow: true,
  allowKong: true,
  sevenPairs: true,
  points: true,
  chips: false,
  startingPoints: 0,
  startingChips: 1000,
  chipsPerPoint: 1,
  scoreMultiplier: 1,
  meldPriority: 'pung-first' as const,
  dealerRepeats: false,
  openTanyao: true,
  kiriage: true,
  uraDora: true,
  taiCap: 5,
  sgAnimals: true,
  sgFlowers: true,
  sgInstantBonuses: true,
  sgBonusUnit: 2,
  sgBase: 1,
  sgSelfDraw: 2,
  houseBonuses: [],
};
export const PRESETS: Record<Preset, Rules> = {
  mcr: { ...common, id: 'mcr', name: 'Chinese MCR', preset: 'mcr', minimum: 8 },
  riichi: {
    ...common,
    id: 'riichi',
    name: 'Japanese Riichi',
    preset: 'riichi',
    rounds: 2,
    minimum: 1,
    startingPoints: 30000,
    dealerRepeats: true,
    meldPriority: 'equal',
  },
  singapore: {
    ...common,
    id: 'singapore',
    name: 'Singapore',
    preset: 'singapore',
    minimum: 1,
    sevenPairs: false,
    dealerRepeats: true,
  },
};
export const PRESET_DETAILS = {
  mcr: {
    subtitle: 'The art of possibility',
    region: 'CHINESE OFFICIAL',
    description: '81 scoring patterns. A world of ways to win.',
    tiles: 144,
    minimum: '8 fan minimum',
    source: 'WMO · 2006 Competition Rules',
  },
  riichi: {
    subtitle: 'Every discard tells a story',
    region: 'JAPANESE',
    description: 'Declare riichi. Read the table. Find your moment.',
    tiles: 136,
    minimum: '1 yaku minimum',
    source: 'EMA · 2025 + June 2026 annotations',
  },
  singapore: {
    subtitle: 'A little more good fortune',
    region: 'SINGAPOREAN',
    description: 'Flowers, animals, and familiar table traditions.',
    tiles: 148,
    minimum: '1 tai minimum',
    source: 'SingaporeMahjong.com · Four Winds profile v1',
  },
};
